[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
update_changelog_on_bump = true
version_scheme = "semver"
version = "0.2.1-b0"
version_files = ["packages/pic/package.json"]
